# entry looks like this:
# [AaveV3."0x5faab9e1adbddad0a08734be8a52185fd6558e14"]
# init_block = 18979624
#
# [[AaveV3."0x5faab9e1adbddad0a08734be8a52185fd6558e14".token_info]]
# address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
# decimals = 6
# symbol = "USDC"
#
# [[AaveV3."0x5faab9e1adbddad0a08734be8a52185fd6558e14".token_info]]
# address = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
# decimals = 8
# symbol = "WBTC"
# However, if token info is not relevant for this pool, you don't have to specify it.

[AaveV3."0x5faab9e1adbddad0a08734be8a52185fd6558e14"]
init_block = 18979624
[AaveV2."0xb9184a4480830bf89b55b73631e287df9079f466"]
init_block = 18129018


[MakerPSM."0x89B78CfA322F6C5dE0aBcEecab66Aee45393cC5A"]
init_block = 11478006

[[MakerPSM."0x89B78CfA322F6C5dE0aBcEecab66Aee45393cC5A".token_info]]
address = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
decimals = 18
symbol = "DAI"

[[MakerPSM."0x89B78CfA322F6C5dE0aBcEecab66Aee45393cC5A".token_info]]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
symbol = "USDC"

[MakerPSM."0x961Ae24a1Ceba861D1FDf723794f6024Dc5485Cf"]
init_block = 13057085

[MakerDssFlash."0x60744434d6339a6B27d73d9Eda62b6F66a0a04FA"]
init_block = 14787503

[[MakerPSM."0x961Ae24a1Ceba861D1FDf723794f6024Dc5485Cf".token_info]]
address = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
decimals = 18
symbol = "DAI"

[[MakerPSM."0x961Ae24a1Ceba861D1FDf723794f6024Dc5485Cf".token_info]]
address = "0x8E870D67F660D95d5be530380D0eC0bd388289E1"
decimals = 18
symbol = "USDP"


[UniswapX."0x6000da47483062a0d734ba3dc7576ce6a0b645c4"]
init_block = 17777988

[BalancerV2."0xBA12222222228d8Ba445958a75a0704d566BF2C8"]
init_block = 12272146

[BalancerV1."0x92E7Eb99a38C8eB655B15467774C6d56Fb810BC9"]
init_block = 10866521

[[BalancerV1."0x92E7Eb99a38C8eB655B15467774C6d56Fb810BC9".token_info]]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
symbol = "USDC"

[[BalancerV1."0x92E7Eb99a38C8eB655B15467774C6d56Fb810BC9".token_info]]
address = "0xf8C3527CC04340b208C854E985240c02F7B7793f"
decimals = 18
symbol = "FRONT"

[Cowswap."0x9008D19f58AAbD9eD0D60971565AA8510560ab41"]
init_block = 12593265

[ZeroX."0xDef1C0ded9bec7F1a1670819833240f027b25EfF"]
init_block = 10247094

# Curve V1 Metapool Implementation Contracts

[CurveV1MetapoolImpl."0x2f956eee002b0debd468cf2e0490d1aec65e027f"]
init_block = 11942426

[CurveV1MetapoolImpl."0x5F890841f657d90E081bAbdB532A05996Af79Fe6"]
init_block = 11942416


# Curve V2 Metapool Implementation Contracts


[CurveV2MetapoolImpl."0xC6A8466d128Fbfd34AdA64a9FFFce325D57C9a52"]
init_block = 12904548

[CurveV2MetapoolImpl."0x55aa9bf126bcabf0bdc17fa9e39ec9239e1ce7a9"]
init_block = 12904527

[CurveV2MetapoolImpl."33bb0e62d5e8c688e645dd46dfb48cd613250067"]
init_block = 14979398

[CurveV2MetapoolImpl."0x213be373FDff327658139C7df330817DAD2d5bBE"]
init_block = 12904519

[CurveV2MetapoolImpl."0xc4C78b08fA0c3d0a312605634461A88184Ecd630"]
init_block = 12904549

[CurveV2MetapoolImpl."0xECAaecd9d2193900b424774133B1f51ae0F29d9E"]
init_block = 13495647

[CurveV2MetapoolImpl."0x40fD58D44cFE63E8517c9Bb3ac98676838Ea56A8"]
init_block = 13495681

[CurveV2MetapoolImpl."0x33bB0e62d5e8C688E645Dd46DFb48Cd613250067"]
init_block = 14979402

[CurveV2MetapoolImpl."0x2EB24483Ef551dA247ab87Cf18e1Cc980073032D"]
init_block = 14979402

[CurveV2MetapoolImpl."0x008CFa89df5B0c780cA3462fc2602D7F8c7Ac315"]
init_block = 16100246

[CurveV2MetapoolImpl."0xAbc533EbCDdeD41215C46ee078C5818B5b0A252F"]
init_block = 16100250

#
#
#
# Curve V2 Plain Pool Implementation Contracts
#
#

[CurveV2PlainPoolImpl."0x4A4d7868390EF5CaC51cDA262888f34bD3025C3F"]
init_block = 12904330

[CurveV2PlainPoolImpl."0x50b085f2e5958c4a87baf93a8ab79f6bec068494"]
init_block = 12904718

[CurveV2PlainPoolImpl."0xe5f4b89e0a16578b3e0e7581327bdb4c712e44de"]
init_block = 12904718

[CurveV2PlainPoolImpl."0x9b52f13df69d79ec5aab6d1ace3157d29b409cc3"]
init_block = 12904716

[CurveV2PlainPoolImpl."0x6326debbaa15bcfe603d831e7d75f4fc10d9b43e"]
init_block = 12904329

[CurveV2PlainPoolImpl."0x24d937143d3f5cf04c72ba112735151a8cae2262"]
init_block = 12904328

[CurveV2PlainPoolImpl."0x6523ac15ec152cb70a334230f6c5d62c5bd963f1"]
init_block = 12904145

#
#
#
# Curve crvUSD Plain Pool Implementation Contracts
#
#

[CurvecrvUSDPlainPoolImpl."0x67fe41a94e779ccfa22cff02cc2957dc9c0e4286"]
init_block = 17258001

[CurvecrvUSDPlainPoolImpl."0x36dc03c0e12a1c241306a6a8f327fe28ba2be5b0"]
init_block = 18277096

[CurvecrvUSDPlainPoolImpl."0x0c9d8c7e486e822c29488ff51bff0167b4650953"]
init_block = 18163376

[CurvecrvUSDPlainPoolImpl."0x7ca46a636b02d4abc66883d7ff164bde506dc66a"]
init_block = 18163373

[CompoundV2."0x99ee778B9A6205657DD03B2B91415C8646d521ec"]
init_block = 8983559

[OneInchV5."0x1111111254EEB25477B68fb85Ed929f73A960582"]
init_block = 19246323

[OneInchFusion."0xA88800CD213dA5Ae406ce248380802BD53b47647"]
init_block = 16792677

[ClipperExchange."0x655eDCE464CC797526600a462A8154650EEe4B77"]
init_block = 16908406

# DVM Factory
[Dodo."0x72d220ce168c4f361dd4dee5d826a01ad8598f6c"]
init_block = 11704651

# DSP Factory
[Dodo."0x6fdDB76c93299D985f4d3FC7ac468F9A168577A4"]
init_block = 12269078

# DPP Factory
[Dodo."0x5336edE8F971339F6c0e304c66ba16F1296A2Fbe"]
init_block = 13397058

 
# Uni V4 Pool Manager
[UniswapV4."0x000000000004444c5dc75cB358380D2e3dE08A90"]
init_block = 21688329

[FluidDex."0x836951EB21F3Df98273517B7249dCEFF270d34bf"]
init_block = 21354360

[[FluidDex."0x836951EB21F3Df98273517B7249dCEFF270d34bf".token_info]]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
symbol = "USDC"

[[FluidDex."0x836951EB21F3Df98273517B7249dCEFF270d34bf".token_info]]
address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
decimals = 18
symbol = "WETH"

[FluidDex."0x0B1a513ee24972DAEf112bC777a5610d4325C9e7"]
init_block = 21016132

[[FluidDex."0x0B1a513ee24972DAEf112bC777a5610d4325C9e7".token_info]]
address  = "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
decimals = 18
symbol   = "wstETH"

[[FluidDex."0x0B1a513ee24972DAEf112bC777a5610d4325C9e7".token_info]]
address  = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
decimals = 18
symbol   = "WETH"

[FluidDex."0x667701e51B4D1Ca244F17C78F7aB8744B4C99F9B"]
init_block = 21016138
 
[[FluidDex."0x667701e51B4D1Ca244F17C78F7aB8744B4C99F9B".token_info]]
address  = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
symbol   = "USDC"

[[FluidDex."0x667701e51B4D1Ca244F17C78F7aB8744B4C99F9B".token_info]]
address  = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
decimals = 6
symbol   = "USDT"

[FluidDex."0x3C0441B42195F4aD6aa9a0978E06096ea616CDa7"]
init_block = 21016165


[[FluidDex."0x3C0441B42195F4aD6aa9a0978E06096ea616CDa7".token_info]]
address  = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
decimals = 8
symbol   = "WBTC"

[[FluidDex."0x3C0441B42195F4aD6aa9a0978E06096ea616CDa7".token_info]]
address  = "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
decimals = 8
symbol   = "cbBTC"

[FluidDex."0xdE632C3a214D5f14C1d8ddF0b92F8BCd188fee45"]
init_block = 21031805

[[FluidDex."0xdE632C3a214D5f14C1d8ddF0b92F8BCd188fee45".token_info]]
address  = "0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f"
decimals = 18
symbol   = "GHO"

[[FluidDex."0xdE632C3a214D5f14C1d8ddF0b92F8BCd188fee45".token_info]]
address  = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
symbol   = "USDC"

[FluidDex."0x97479d9C09c7Fd333bBfd07e93d4c8a669698EBc"]
init_block = 21845426


[[FluidDex."0x97479d9C09c7Fd333bBfd07e93d4c8a669698EBc".token_info]]
address  = "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
decimals = 8
symbol   = "cbBTC"

[[FluidDex."0x97479d9C09c7Fd333bBfd07e93d4c8a669698EBc".token_info]]
address  = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
decimals = 18
symbol   = "WETH"


[FluidDex."0xD0810e5CF08dCDe266ecEBEf40caD806c7768D72"]
init_block = 21744576


[[FluidDex."0xD0810e5CF08dCDe266ecEBEf40caD806c7768D72".token_info]]
address  = "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf"
decimals = 8
symbol   = "cbBTC"

[[FluidDex."0xD0810e5CF08dCDe266ecEBEf40caD806c7768D72".token_info]]
address  = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
decimals = 6
symbol   = "USDT"











# [PropellerLabsSolver."0x14f2b6ca0324cd2B013aD02a7D85541d215e2906"]
# init_block = 19025601
